// Generated by CoffeeScript 1.6.1
(function() {

  define(['jquery', 'underscore', 'backbone', 'router'], function($, _, Backbone, Router) {
    var initialize;
    initialize = function() {
      return Router.initialize();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
