// Generated by CoffeeScript 1.6.1
(function() {

  require.config({
    paths: {
      jquery: 'libs/jquery.min',
      underscore: 'libs/underscore.min',
      backbone: 'libs/backbone.min',
      accordionView: 'views/AccordionView'
    }
  });

  /*
  require ['app'], (App) ->
    do App.initialize
  */


}).call(this);
