// Generated by CoffeeScript 1.6.1
(function() {

  define(['jquery', 'underscore', 'backbone', 'accordionView'], function($, _, Backbone, AccordionView) {
    var AppRouter, initialize;
    AppRouter = Backbone.Router.extend({
      routes: {
        '*actions': 'defaultAction'
      }
    });
    initialize = function() {
      var app_router;
      app_router = new AppRouter;
      app_router.on('route:defaultAction', function(actions) {
        var accordionView;
        console.info('default');
        return accordionView = new AccordionView({
          el: '#main',
          heading: 'h2'
        });
      });
      return Backbone.history.start();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
